# PANDAS SERIES AND DATAFRAME

In [40]:
from pandas import Series, DataFrame
import pandas as pd

## 1. Cấu trúc dữ liệu Series
### Khái niệm Series
**Series** là một cấu trúc dữ liệu dạng **mảng một chiều (one-dimensional array)** trong thư viện **Pandas**.  
Nó bao gồm hai thành phần chính:
- **values**  
  Mảng dữ liệu thực tế chứa các giá trị.
- **index**  
  Mảng nhãn dùng để định danh cho từng phần tử trong Series.
dO ĐÓ, mỗi phần tử trong Series luôn có dạng:
index -> value

In [41]:
#Series
obj = Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

## Truy cập thành phần của Series
### Thuộc tính values và index

In [42]:
obj1= obj.values
obj2= obj.index
print ("Value:", obj1)
print ("Index:", list(obj2))

Value: [ 4  7 -5  3]
Index: [0, 1, 2, 3]

### Khởi tạo Series với chỉ mục tùy chỉnh
Series có thể được tạo với **index tùy ý** thay vì index mặc định

In [43]:
obj2 = Series([4, 5, -3, 7], index = ['d', 'c', 'a', 'e'])
obj2

d    4
c    5
a   -3
e    7
dtype: int64

In [44]:
#Truy xuất 1 phần tử
print(obj2['a'])

-3

In [45]:
#truy xuất nhiều phàn tử
print(obj2[['c','a','d']].values)

[ 5 -3  4]

## Các phép toán trên Series
Series hỗ trợ các phép toán giống Numpy đồng thời bảo toàn mối liên kết giữa index và value

In [46]:
#Lọc dữ liệu bằng Boolean
print(obj2[obj2 > 0].to_string())

d    4
c    5
e    7

In [47]:
#Phép toán số học
print((obj2*2).to_string())

d     8
c    10
a    -6
e    14

In [48]:
#Áp dụng hàm toán học
import numpy as np
print ((np.exp(obj2)).to_string())

d      54.598150
c     148.413159
a       0.049787
e    1096.633158

## Series như một cấu trúc ánh xạ
Series có thể được xem như một ánh xạ (mapping) giữa:
index -> value
Do đó nó có hành vi tương tự như dictionary

In [49]:
#Ví dụ kiểm tra khóa
'b' in obj2

False

In [50]:
'e' in obj2

True

In [51]:
# Khởi tạo Series từ Dictionary
obj3 = {
'Ohio': 35000,
'Texas': 71000,
'Oregon': 16000,
'Utah': 5000
}
print ((Series(obj3)).to_string())

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000

Trong trường hợp này:
- key của dict -> index
- value của dict -> dữ liệu

## Dữ liệu thiếu trong Series
Nếu chỉ mục yêu cầu không tồn tại trong dữ liệu, Pandas sẽ gán giá trị **NaN (Not a Number)**

In [52]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series(obj3, index=states)
print (obj4.to_string())

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0

## Phát hiện dữ liệu thiếu
Pandas cung cấp hai hàm để kiểm tra dữ liệu thiếu
- isnull()
- notnull()

In [53]:
print((pd.isnull(obj4).to_string()))

California     True
Ohio          False
Oregon        False
Texas         False

In [54]:
print((pd.notnull(obj4)).to_string())

California    False
Ohio           True
Oregon         True
Texas          True

## Căn chỉnh chỉ mục tự động trong phép toán
Một đặc điểm quan trọng của Series là tự động căn chỉnh index khi thực hiện phép toán.
Nguyên tắc:
- Chỉ các **index trùng nhau** mới thực hiện phép tính.
- Index không tồn tại ở một Series sẽ có giá trị N.

In [55]:
Series(obj3) + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

## Thuộc tính name của Series và Index
Series và index đều có thuộc tính name để mô tả dữ liệu.
Ý nghĩa:
- **name của Series**: mô tả dữ liệu values.
- **name của index**: mô tả bản chất của nhãn chỉ mục.

In [56]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

## Thay đổi chỉ mục của Series
Index của seriese có thể được thay đổi bằng phép gán trực tiếp

In [57]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']
print (obj.to_string())

Bob      4
Steve    7
Jeff    -5
Ryan     3

## Mối liên hệ giữa các nội dung
Các đặc điểm của Series có mối liên hệ chặt chẽ với nhau:
- Series = values + index
- index cho phép truy cập dữ liệu theo nhãn
- NumPy operations hoạt động trực tiếp trên values
- NaN hỗ trợ xử lý dữ liệu thiếu
- automatic alignment giúp tính toán trên dữ liệu có index khác nhau
- dictionary mapping cho phép tạo Series linh hoạt

## Tóm tắt về Series Pandas
Series là cấu trúc dữ liệu cơ bản của Pandas, dùng để biểu diễn dữ liệu một chiều có gắn nhãn chỉ mục. Nó kết hợp các đặc điểm của:
- mảng NumPy (tính toán nhanh)
- dictionary (truy cập theo nhãn)

<br> Các khả năng quan trọng của Series bao gồm:
- quản lý dữ liệu theo index
- hỗ trợ phép toán NumPy
- phát hiện dữ liệu thiếu (NaN)
- tự động căn chỉnh dữ liệu khi tính toán

<br> Nhờ các đặc tính này, Series trở thành thành phần nền tảng cho việc xây dựng các cấu trúc dữ liệu phức tạp hơn trong Pandas như DataFrame, đồng thời đóng vai trò quan trọng trong tiền xử lý và phân tích dữ liệu.

# 2. DataFrame
Trong thư viện **Pandas**, bên cạnh **Series**, cấu trúc dữ liệu quan trọng thứ hai là **DataFrame**.
**DataFrame** biểu diễn dữ liệu dưới dạng bảng hai chiều *(two-dimensional table)* tương tự như bảng tính *(spreadsheet)* hoặc bảng dữ liệu trong cơ sở dữ liệu.

Mỗi cột *(column)* trong DataFrame có thể chứa kiểu dữ liệu khác nhau như:
- số *(numeric)*
- chuỗi *(string)*
- boolean

DataFrame là một cấu trúc dữ liệu hai chiều:
- **index hàng (row index)**
- **index cột (column labels)**

Về bản chất, **DataFrame** có thể được xem như một **dict của các Series**, trong đó mỗi cột là một Series chia sẻ cùng chỉ mục hàng.

### Khởi tạo DataFrame

In [58]:
#Khởi tạo từ Dictionary
data = {
'state': ['Ohio','Ohio','Ohio','Nevada','Nevada'],
'year': [2000,2001,2002,2001,2002],
'pop': [1.5,1.7,3.6,2.4,2.9]
}
frame =DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

### Chỉ định thứ tự cột
Thứ tự cột có thể được xác định bằng tham số columns

In [59]:
DataFrame(data, columns=['year', 'state', 'pop'])

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

### Thêm cột không tồn tại
Nếu khai báo một cột không có trong dữ liệu ban đầu, Pandass sẽ gán giá trị NA (Not Available)

In [60]:
frame2 = DataFrame(data, columns = ['year', 'state', 'pop', 'debt'],
index = ['one', 'two', 'three', 'four', 'five'])
frame2
#NaN biểu diễn dữ liệu bị thiếu (missing data)

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

## Truy xuất dữ liệu trong DataFrame
### Truy xuất cột
Một cột trong DataFrame có thể được truy xuất theo hai cách:
- Cách 1: Sử dụng tên cột
- Cách 2: Sử dụng thuộc tính

In [61]:
#Cách 1
print((frame2['state']).to_string())

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada

In [62]:
#Cách 2
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

### Truy xuất hàng
Hàng có thể được truy xuất bằng phương thức lập chỉ mục

In [63]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

## Thao tác với cột trong DataFrame
### Gán giá trị cho cột
Có thể gán giá trị vô hướng (scalar) cho toàn bộ cột

In [64]:
frame2['debt'] = 16.5
frame2
#Mọi phần tử của cột debt =16.5

       year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

### Gán mảng giá trị cho cột
Có thể gán list hoặc Numpy array cho cột. Điều kiện độ dài mảng phải bằng số hàng của DataFrame

In [65]:
frame2['debt']= np.arange(5.)
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

### Gán Series vào DataFrame
Có thể sử dụng Serires để tạo cột mới. Các giá trị sẽ tự động căn chỉnh theo index. Các vị trí không có giá trị sẽ nhận NaN.
- Kết quả:
+ Các giá trị sẽ tự động căn chỉnh theo index.
+ Các vị trí không có giá trị sẽ nhận NaN.

In [66]:
val = Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
frame2 ['debt'] = val
frame2

       year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

## Tạo và xóa cột
### Tạo cột mới
Một cột có thể được tạo từ phép toán trên cột khác.

In [67]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

       year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

### Xóa cột
Cột có thể bị xóa bằng lệnh

In [ ]:
del frame2['eastern']
#Chạy lệnh này xong đã xoán eastern khi chạy lại lần nữa sẽ ra lỗi vì đã không còn cột đó nữa

## Khởi tạo DataFrame từ dictionary lồng nhau
DataFrame có thể được tạo từ dict của dict.
Trong trường hợp này:
- dict ngoài -> cột
- dict trong -> index hàng

In [69]:
pop ={
    'Nevada' :{2001:2.4, 2002:2.9},
    'Ohio': {2000: 1.5, 2001:1.7, 2002:3.6}
}
frame3 = DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

## Phép chuyển vị
DataFrame có thể chuyển đổi hàng <-> cột bằng phép chuyển vị (transpose).

In [70]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

### Thuộc tính values
Thuộc tính values cho phép truy xuất mảng Numpy chứa dữ liệu của DataFrame.
Nếu dataframe có nhiều kiểu dữ liệu khách nhau, mảng trả về sẽ có kiểu:
+ dtype= object

In [71]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

### Thuộc tính Index trong Pandas
Index là đối tượng lưu trữ nhãn của các trục dữ liệu

In [73]:
obj = Series (range(3), index =['a', 'b', 'c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='str')

### Index hỗ trợ phép toán tập hợp
Index có hành vi giống list và set do đó có thể thực hiện các phép kiểm tra.

In [75]:
'Ohio' in frame3.columns

True

In [76]:
2003 in frame3.index

False

## TÓM TẮT
### Các cách khởi tạo DataFrame
Một DataFrame có thể được tạo từ nhiều nguồn dữ liệu khác nhau, bao gồm:
- **1. 2D ndarray** – ma trận dữ liệu hai chiều
- **2. dict của list hoặc tuple** – mỗi list là một cột
- **3. dict của Series** – mỗi Series là một cột
- **4. dict của dict** – key ngoài là cột, key trong là index
- **5. list của dict hoặc Series** – mỗi phần tử là một hàng
- **6. list của list hoặc tuple** – dữ liệu bảng hai chiều
- **7. DataFrame khác** – sao chép cấu trúc
- **8. NumPy sparse array** – dữ liệu thưa
### Mối liên hệ giữa DataFrame, Series và Index
Các cấu trúc dữ liệu trong Pandas có mối quan hệ chặt chẽ:
- **Series**: dữ liệu một chiều
- **DataFrame**: tập hợp nhiều series
- **Index**: nhãn định danh cho các trục dữ liệu

Cụ thể:
DataFrame = tập hợp các Series (columns) + Index (hàng)
Index cung cấp khả năng truy cập theo nhãn và hỗ trợ các phép toán tập hợp,
trong khi Series cung cấp khả năng tính toán và quản lý dữ liệu theo index. Sự kết hợp này tạo nên sức mạnh của Pandas trong việc xử lý dữ liệu phức tạp.
### Kết luận
DataFrame là cấu trúc dữ liệu trung tâm của thư viện Pandas, được thiết kế để lưu trữ và thao tác với dữ liệu dạng bảng hai chiều.

Các đặc điểm quan trọng của DataFrame gồm:
- Lưu trữ dữ liệu theo hàng và cột
- Cho phép mỗi cột có kiểu dữ liệu khác nhau
- Hỗ trợ truy xuất dữ liệu linh hoạt
- Xử lý dữ liệu thiếu (NaN)
- Cho phép tạo, sửa và xoá cột
- Hỗ trợ nhiều phương pháp khởi tạo dữ liệu

Nhờ những đặc điểm này, DataFrame trở thành công cụ quan trọng trong tiền xử lý dữ liệu (Data Preprocessing – tiền xử lý dữ liệu) và phân tích dữ liệu bằng Python.